export const styles=`
.dsh-remote{container-type:inline-size;color:inherit;font-size:14px;line-height:1.6;padding:20px 0;max-width:760px;min-width:0;--rm-line:color-mix(in srgb,currentColor 12%,transparent);--rm-soft:color-mix(in srgb,currentColor 4%,transparent);--rm-muted:color-mix(in srgb,currentColor 58%,transparent);--rm-accent:var(--dsw-alias-brand-primary,#4d6bfe)}
.dsh-remote *{box-sizing:border-box}.dsh-remote h2{font-size:18px;font-weight:600;margin:0}.dsh-remote h3{font-size:14px;font-weight:600;margin:0}.dsh-remote p{margin:5px 0 0;font-size:12px;color:var(--rm-muted);line-height:1.7}
.dsh-remote .rm-head{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:20px}.dsh-remote .rm-switch{display:inline-flex;position:relative;flex-shrink:0;width:38px;height:24px;cursor:pointer}.dsh-remote .rm-switch input{position:absolute;opacity:0;width:100%;height:100%;margin:0;cursor:inherit}.dsh-remote .rm-switch span{width:38px;height:24px;background:color-mix(in srgb,currentColor 22%,transparent);border-radius:20px;pointer-events:none;transition:background .15s}.dsh-remote .rm-switch span:after{content:'';display:block;width:18px;height:18px;background:white;border-radius:50%;margin:3px;box-shadow:0 1px 3px #0002;transition:transform .15s}.dsh-remote .rm-switch input:checked+span{background:var(--rm-accent)}.dsh-remote .rm-switch input:checked+span:after{transform:translateX(14px)}.dsh-remote .rm-switch input:focus-visible+span{outline:2px solid var(--rm-accent);outline-offset:3px}.dsh-remote .rm-switch input:disabled+span{opacity:.45}
.dsh-remote .rm-card{border:1px solid var(--rm-line);border-radius:14px;overflow:hidden;margin-bottom:20px}.dsh-remote .rm-device,.dsh-remote .rm-row{display:grid;align-items:center;gap:16px;padding:16px 18px;min-width:0}.dsh-remote .rm-device{grid-template-columns:minmax(80px,1fr) minmax(0,260px)}.dsh-remote .rm-row{grid-template-columns:minmax(62px,1fr) minmax(100px,128px) minmax(140px,180px)}.dsh-remote .rm-row+.rm-row{border-top:1px solid var(--rm-line)}.dsh-remote .rm-row strong{font-size:14px;font-weight:500}.dsh-remote .rm-section{margin:0 0 10px}.dsh-remote .rm-code{display:grid;gap:4px;font-size:11px;color:var(--rm-muted)}
.dsh-remote select,.dsh-remote .rm-learn{font:inherit;color:inherit;border:1px solid var(--rm-line);background:var(--dsw-specific-input-major,transparent);border-radius:9px;padding:9px 10px;min-height:42px;width:100%;min-width:0}.dsh-remote select{cursor:pointer;padding-right:28px;appearance:none;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath d='m3 4.5 3 3 3-3' fill='none' stroke='%23888888' stroke-width='1.5' stroke-linecap='round'/%3E%3C/svg%3E");background-repeat:no-repeat;background-position:right 10px center;text-overflow:ellipsis}.dsh-remote .rm-learn{cursor:pointer;text-align:center;color:var(--dsw-alias-label-primary,inherit);font-size:13px;font-variant-numeric:tabular-nums}.dsh-remote option{color:CanvasText;background:Canvas}.dsh-remote select:focus-visible,.dsh-remote .rm-learn:focus-visible{outline:2px solid var(--rm-accent);outline-offset:2px}.dsh-remote select:disabled,.dsh-remote .rm-learn:disabled{opacity:.45;cursor:default}
.dsh-remote .rm-learn.is-learning{border-color:var(--rm-accent);color:var(--rm-accent);background:color-mix(in srgb,var(--rm-accent) 8%,transparent)}.dsh-remote .rm-capture-hint{font-size:12px;color:var(--rm-muted);line-height:1.7;min-height:42px;margin-top:-6px}.dsh-remote .rm-binding{display:grid;gap:6px;min-width:0}.dsh-remote .rm-bound-key{font-size:11px;color:var(--rm-muted);font-variant-numeric:tabular-nums;overflow-wrap:anywhere;line-height:1.5}.dsh-remote .rm-note{margin-top:12px}.dsh-remote details{margin-top:18px;padding-top:14px;border-top:1px solid var(--rm-line)}.dsh-remote summary{cursor:pointer;font-size:12px;color:var(--rm-muted);padding:6px 0}.dsh-remote .rm-diagnostic{overflow-wrap:anywhere;font-size:12px}.dsh-remote .rm-error{color:#c64747;margin-top:12px}
@container(max-width:460px){.dsh-remote .rm-device{grid-template-columns:1fr;gap:10px}.dsh-remote .rm-row{grid-template-columns:minmax(0,1fr) minmax(120px,1.35fr);gap:10px;padding:14px 12px}.dsh-remote .rm-row strong{grid-column:1/-1}.dsh-remote .rm-code{grid-template-columns:28px minmax(0,1fr);align-items:center;gap:6px}.dsh-remote .rm-device{padding:14px 12px}.dsh-remote .rm-head{gap:12px}}
`
