package com.dsharnessmobile.shell

import android.content.Context
import android.media.MediaScannerConnection
import android.os.Environment
import android.util.Log
import java.io.File
import java.nio.file.Files

/**
 * Owns the embedded Termux environment snapshot: first-launch extraction into
 * filesDir/usr and the dsh engine process lifecycle (PATH/LD_LIBRARY_PATH/HOME
 * injected explicitly — the snapshot is self-sufficient, no Termux app needed).
 */
class EngineManager(private val context: Context, private val pickToken: String? = null) {

  val usrDir = File(context.filesDir, "usr")
  val homeDir = File(context.filesDir, "home")

  /**
   * Public export repo: /storage/emulated/0/Documents/dshdata.
   * Holds only user-initiated session zip exports (exports/) plus a .nomedia anti-scan marker;
   * all runtime user data lives back in private app data (files/home/.dsh).
   */
  val dshDataDir: File
    get() {
      val publicDocs = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS)
        ?: File(context.filesDir, "dshdata-fallback")
      return File(publicDocs, "dshdata")
    }
  private val nodeBin = File(usrDir, "bin/node")
  private val dshBin = File(usrDir, "lib/node_modules/@deepseek-ai/dsh/lib/bin.js")
  /** The engine Process is process-owned, not Activity-owned: MainActivity and
   * EngineService create separate managers but must observe the same child. */
  private var engineProcess: Process?
    get() = sharedEngineProcess
    set(value) {
      sharedEngineProcess = value
    }

  /** Consecutive healthy probe ticks since the last update swap (update-v2 confirmation state). */
  private var updateHealthTicks = 0

  val engineReady: Boolean get() = nodeBin.exists()

  /**
   * Deploy the undo emergency CLI (assets/undo-emergency.mjs → filesDir).
   * Idempotent: content equals the asset → skip. Missing node still succeeds
   * (the file itself is versioned with the app); UndoGate checks child exit code.
   */
  fun deployUndoCli() {
    try {
      val asset = "undo-emergency.mjs"
      if (context.assets.open(asset).use { it.readBytes() }.let { b ->
          File(context.filesDir, asset).takeIf { it.exists() }?.readBytes()?.contentEquals(b) != true
        }) {
        context.assets.open(asset).use { input ->
          File(context.filesDir, asset).outputStream().use { input.copyTo(it) }
        }
        Log.i(TAG, "undo emergency CLI deployed")
      }
    } catch (t: Throwable) {
      Log.e(TAG, "undo CLI deploy failed (non-fatal): " + t.message)
    }
  }

  /** Embedded snapshot fingerprint (assets/snapshot.sha256, generated by build-release.ps1). */
  private fun bundledFingerprint(): String = try {
    context.assets.open("snapshot.sha256").bufferedReader().use { it.readText().trim() }
  } catch (_: Exception) {
    ""
  }

  private fun fingerprintFile(): File = File(context.filesDir, ".snapshot-fingerprint")

  /**
   * Whether the snapshot is extracted and matches the embedded version: node exists + fingerprint match.
   * Upgrade lesson (v0.10.5→v0.10.6): engineReady only checked node existence, so an upgrade never
   * re-extracted → old plugins kept running (injection-guard fixes etc. never took effect).
   */
  fun snapshotFresh(): Boolean {
    if (!nodeBin.exists()) return false
    val fp = bundledFingerprint()
    if (fp.isEmpty()) return true // no fingerprint file (legacy build): don't force a re-extract
    return fingerprintFile().exists() && fingerprintFile().readText().trim() == fp
  }

  /**
   * Upgrade/snapshot change: extract the embedded snapshot into a staging directory, then
   * activate it as one transaction. The live runtime is untouched while the archive is being
   * extracted, so an interruption cannot leave a half-old/half-new tree; the swap itself only
   * renames factory-owned entries and never touches user data (sessions, attachments, settings,
   * credentials, workspaces, undo history, model metadata, compile cache).
   *
   * The transaction marker makes the next start deterministic: a staged-only run is discarded,
   * an interrupted swap is rolled back to the previous factory tree, and a swap whose commit
   * write was lost is rolled forward. See [SnapshotTransaction].
   */
  fun refreshSnapshot(
    onProgress: (Long, Long) -> Unit,
    onStage: (String) -> Unit = {},
  ): Boolean {
    val filesDir = context.filesDir
    val fingerprint = bundledFingerprint()
    val startedAt = System.currentTimeMillis()
    val stage = SnapshotTransaction.stageRoot(filesDir)
    EngineManager.snapshotRefreshing = true
    try {
      onStage("正在检查上次更新…")
      applyRecovery(SnapshotTransaction.recover(filesDir, stage, usrDir, homeDir, liveFingerprint()))
      if (snapshotFresh()) {
        // A rolled-forward transaction already activated this snapshot.
        return true
      }

      onStage("正在解压运行时…")
      SnapshotFs.deletePath(stage)
      SnapshotFs.createDirectories(stage)
      if (!extractSnapshotTo(stage, onProgress)) {
        SnapshotFs.deletePath(stage)
        Log.e(TAG, "snapshot refresh: extract failed; live runtime untouched")
        return false
      }
      if (!stagedRuntimeComplete(stage)) {
        SnapshotFs.deletePath(stage)
        Log.e(TAG, "snapshot refresh: staged runtime incomplete; live runtime untouched")
        return false
      }

      onStage("正在恢复用户数据…")
      restoreLegacyUserData(File(homeDir, ".dsh"))
      // 0.13.5 W1a（issue #126 P1 的兜底诉求）：换树前留一份 settings.yaml 快照。
      // 事务化本身从不触碰用户数据，这份副本是「万一」时的取证/回滚来源——
      // 只保留最近 3 代，写失败仅告警（不阻断刷新）。
      snapshotSettingsBackup()

      onStage("正在完成运行时更新…")
      SnapshotTransaction.writeMarker(
        filesDir,
        SnapshotTransaction.Marker(SnapshotTransaction.Phase.STAGED, fingerprint, startedAt),
      )
      val swapNotes = SnapshotTransaction.swap(
        filesDir = filesDir,
        stagedRoot = stage,
        usrDir = usrDir,
        homeDir = homeDir,
        preservedNames = SnapshotUserData.preservedNames.toSet(),
        fingerprint = fingerprint,
        startedAt = startedAt,
        onEntry = { onStage("正在更新 " + it) },
      )
      // #214：profiles 合并期间的工厂语义纠正逐条留档（升级现场可追溯，不只依赖 UI 文案）。
      for (note in swapNotes) LogCollector.log(TAG, "profile patch reconciled during swap: " + note)
      // Commit point: the fingerprint is durable only after the swap completed.
      writeFingerprint(fingerprint)
      SnapshotTransaction.finish(filesDir)
      Log.i(TAG, "snapshot refreshed (fingerprint " + fingerprint.take(12) + ")")
      return true
    } catch (t: Throwable) {
      Log.e(TAG, "snapshot refresh failed; rolling back", t)
      onStage("运行时更新失败，正在回滚…")
      try {
        val marker = SnapshotTransaction.readMarker(filesDir)
        if (marker != null) {
          SnapshotTransaction.rollback(filesDir, stage, usrDir, homeDir, marker)
          SnapshotTransaction.clearMarker(filesDir)
        } else {
          SnapshotFs.deletePath(stage)
        }
      } catch (rollbackError: Throwable) {
        // Keep the marker: the next start retries the rollback before anything else.
        Log.e(TAG, "snapshot refresh rollback failed; recovery marker retained", rollbackError)
      }
      return false
    } finally {
      EngineManager.snapshotRefreshing = false
    }
  }

  /**
   * Resolves a transaction interrupted by a kill, an OEM cleaner or a low-memory restart.
   * Cheap when nothing is pending (one stat) and safe to call on every start.
   */
  fun recoverInterruptedRefresh() {
    // Another refresh owns the stage/previous trees right now: never race it.
    if (EngineManager.snapshotRefreshing) return
    val filesDir = context.filesDir
    val marker = SnapshotTransaction.readMarker(filesDir)
    if (marker == null) {
      // No marker: only a stale stage directory can survive (a rollback that was
      // interrupted before it deleted the stage).
      SnapshotFs.deletePath(SnapshotTransaction.stageRoot(filesDir))
      return
    }
    EngineManager.snapshotRefreshing = true
    try {
      applyRecovery(
        SnapshotTransaction.recover(filesDir, SnapshotTransaction.stageRoot(filesDir), usrDir, homeDir, liveFingerprint()),
      )
    } catch (t: Throwable) {
      Log.e(TAG, "snapshot transaction recovery failed; marker retained", t)
    } finally {
      EngineManager.snapshotRefreshing = false
    }
  }

  private fun applyRecovery(recovery: SnapshotTransaction.Recovery) {
    when (recovery.outcome) {
      SnapshotTransaction.Outcome.NONE -> return
      SnapshotTransaction.Outcome.DISCARDED_STAGE -> {
        Log.w(TAG, "interrupted refresh discarded (staged runtime was never activated)")
      }
      SnapshotTransaction.Outcome.ROLLED_BACK -> {
        Log.w(TAG, "interrupted refresh rolled back to the previous factory runtime")
      }
      SnapshotTransaction.Outcome.ROLLED_FORWARD -> {
        val fingerprint = recovery.fingerprintToCommit
        if (!fingerprint.isNullOrEmpty()) writeFingerprint(fingerprint)
        SnapshotTransaction.finish(context.filesDir)
        Log.w(TAG, "interrupted refresh completed (runtime was already activated)")
      }
    }
  }

  private fun liveFingerprint(): String = try {
    fingerprintFile().takeIf { it.exists() }?.readText()?.trim() ?: ""
  } catch (_: Throwable) {
    ""
  }

  /** The fingerprint is the transaction commit point, so it is written atomically. */
  private fun writeFingerprint(fingerprint: String) {
    val target = fingerprintFile()
    val tmp = File(target.parentFile, target.name + ".tmp")
    tmp.writeText(fingerprint)
    SnapshotFs.deletePath(target)
    if (!tmp.renameTo(target)) {
      target.writeText(fingerprint)
      SnapshotFs.deletePath(tmp)
    }
  }

  /** A stage that lacks the engine entry points must never be activated. */
  private fun stagedRuntimeComplete(stage: File): Boolean {
    val node = File(stage, "usr/bin/node")
    val bin = File(stage, "usr/lib/node_modules/@deepseek-ai/dsh/lib/bin.js")
    val profile = File(stage, "home/.dsh/profiles/web")
    val complete = SnapshotFs.exists(node) && SnapshotFs.exists(bin) && SnapshotFs.exists(profile)
    if (!complete) {
      Log.e(
        TAG,
        "staged runtime incomplete: node=" + SnapshotFs.exists(node) +
          " bin=" + SnapshotFs.exists(bin) + " profile=" + SnapshotFs.exists(profile),
      )
    }
    return complete
  }

  /**
   * One-time migration for a `.dsh-backup` left by a pre-transaction refresh (<= 0.13.2).
   * Additive: the backup can only add missing entries, never roll back newer data.
   */
  private fun restoreLegacyUserData(dsh: File) {
    val backup = File(context.filesDir, ".dsh-backup")
    if (!SnapshotFs.exists(backup)) return
    try {
      val result = SnapshotUserData.restoreLegacyBackup(backup, dsh) { link ->
        Log.w(TAG, "legacy user-data restore skipped broken symbolic link: " + link.absolutePath)
      }
      Log.w(
        TAG,
        "legacy user-data backup restored (copied=" + result.copiedEntries +
          " kept=" + result.skippedExisting + " broken=" + result.skippedBrokenLinks + ")",
      )
      SnapshotFs.deletePath(backup)
    } catch (t: Throwable) {
      // Keep the backup for the next attempt; a failed migration must not block the refresh.
      Log.e(TAG, "legacy user-data restore failed; backup retained at " + backup.absolutePath, t)
    }
  }

  /**
   * 0.13.5 W1a：换树前把用户 settings.yaml 复制到 `files/.snapshot-settings-backup/`（保留最近 3 代）。
   *
   * 事务化刷新本身从不移动/覆盖用户数据（[SnapshotTransaction] 跳过 preservedNames），
   * 这份副本回应 issue #126 P1 的诉求：升级出意外时至少有一份「升级前」的配置可取证/回滚。
   * 写入失败只告警——备份不是刷新的前置条件。
   */
  private fun snapshotSettingsBackup() {
    val source = File(File(homeDir, ".dsh"), "settings.yaml")
    if (!SnapshotFs.exists(source)) return
    try {
      val dir = File(context.filesDir, ".snapshot-settings-backup")
      SnapshotFs.createDirectories(dir)
      val stamp = java.text.SimpleDateFormat("yyyyMMdd-HHmmss", java.util.Locale.US).format(java.util.Date())
      val target = File(dir, "settings-$stamp.yaml")
      source.copyTo(target, overwrite = true)
      // 只保留最近 3 代（按文件名时间戳排序，删旧留新）
      val all = dir.listFiles { f -> f.isFile && f.name.startsWith("settings-") }?.sortedBy { it.name } ?: emptyList()
      for (stale in all.dropLast(3)) SnapshotFs.deletePath(stale)
      Log.i(TAG, "settings backup written: " + target.name + " (kept " + minOf(all.size, 3) + ")")
    } catch (t: Throwable) {
      Log.w(TAG, "settings backup failed (non-fatal)", t)
    }
  }

  /** Process-level start guard (MainActivity and EngineService each construct their own EngineManager;
   *  instance fields are invisible across them — the double-start race needs companion-level CAS). */
  private val starting: Boolean
    get() = STARTING.get()

  /**
   * Extract the bundled snapshot archive into [stage]. The live tree is never a
   * destination: extraction is only ever performed inside the transaction stage.
   * @param onProgress bytesDone, bytesTotal.
   * @returns true on success.
   */
  private fun extractSnapshotTo(stage: File, onProgress: (Long, Long) -> Unit): Boolean {
    return try {
      val fd = context.assets.openFd("snapshot.tar.xz")
      SnapshotExtractor.extract(
        context.assets.open("snapshot.tar.xz"), fd.length, stage, onProgress, runtimeRoot = context.filesDir,
      )
      true
    } catch (t: Throwable) {
      Log.e(TAG, "snapshot extract failed", t)
      false
    }
  }

  /**
   * Ensure the private DSH_HOME data layout is ready (idempotent, called from a background thread).
   *
   * Since v0.10.5 all runtime data lives in private app data; Documents/dshdata stays only as the
   * user-initiated export repo (exports/ + .nomedia). This method:
   *  - on a first/clean install: sets up the private .dsh layout and the public export repo;
   *  - when it detects a pre-v0.10.4 public migration layout (.migrated-from or private symlinks):
   *    performs a reverse migration, copying sessions/storages/attachments/profiles/settings.yaml
   *    back into private storage and cleaning up the public leftovers;
   *  - on any failure keeps the public data; the engine still starts with a private DSH_HOME and
   *    retries next time.
   *
   * DSH_HOME always stays in the private domain: the profiles/node_modules flat-fallback symlink
   * mechanism depends on the app-private domain (public FUSE forbids symlinks), so DSH_HOME must
   * never be migrated wholesale.
   */
  /**
   * #130-2：播种「手机操控」Agent 预设（`$DSH_HOME/.agent-presets/phone-control/`）。
   * 组成文件直接复制当前引擎自带的 `standard` 预设（避免随引擎升级漂移），另附 SKILL.md
   * 固定「dump → 按 ref 动作 → 校验 → 再 dump」的流程与纪律。已存在则不覆盖（用户可自改）。
   */
  private fun seedPhoneControlPreset(privateDsh: File) {
    try {
      val dir = File(File(privateDsh, ".agent-presets"), "phone-control")
      // SKILL.md 是我们管理的纪律文案：每次启动都刷新（保证升级后纪律立即生效）；
      // preset.yml / agent.cordis.yml 只在缺失时播种，保留用户可能的改动。
      val skillDir = File(dir, "skills/phone-control").apply { mkdirs() }
      val skillFile = File(skillDir, "SKILL.md")
      if (skillFile.readText().trim() != PHONE_CONTROL_SKILL.trim()) {
        skillFile.writeText(PHONE_CONTROL_SKILL)
        Log.i(TAG, "phone-control SKILL refreshed")
      }
      // 0.13.8 #130/V2 P1-11：标准组合的 skill-filesystem 行没有 config——预设自带的
      // skills 目录不在任何被扫描的 skill 根里，phone-control 的 SKILL 从未被加载
      // （与缺 frontmatter 并列的两处缺陷之一）。结构化后处理：照抄上游 cordis 预设的
      // 写法注入 customSkillDirs（指向本预设 skills/ 目录，baseUrl 相对解析）；
      // 已注入则跳过（幂等）。置于 preset.yml 早退之前——存量用户的升级路径也覆盖。
      val composition = File(dir, "agent.cordis.yml")
      if (composition.exists()) {
        val text = composition.readText()
        if (text.contains("- id: skill-filesystem") && !text.contains("customSkillDirs")) {
          val anchor = "- id: skill-filesystem\n  name: '@deepseek-ai/dsh-skill-filesystem'"
          val injected = anchor + "\n" +
            "  config:\n" +
            "    customSkillDirs:\n" +
            "      - !!js \"process.getBuiltinModule('node:url').fileURLToPath(new URL('skills/', baseUrl))\""
          val patched = text.replace(anchor, injected)
          if (patched != text) {
            composition.writeText(patched)
            Log.i(TAG, "phone-control preset: customSkillDirs injected into skill-filesystem row")
          } else {
            Log.w(TAG, "phone-control preset: skill-filesystem anchor not found; customSkillDirs not injected")
          }
        }
      }
      if (File(dir, "preset.yml").exists()) return
      val shipped = File(
        context.filesDir,
        "usr/lib/node_modules/@deepseek-ai/dsh/node_modules/@deepseek-ai/dsh-agent-presets/presets/standard/agent.cordis.yml",
      )
      if (!shipped.isFile) {
        Log.w(TAG, "phone-control preset skipped: shipped standard composition absent at " + shipped.absolutePath)
        return
      }
      File(dir, "agent.cordis.yml").writeText(shipped.readText())
      File(dir, "preset.yml").writeText(
        "name: 手机操控\n" +
          "description: 以无障碍语义树 / DOM 快照驱动的手机操控预设：dump → 按 ref 点击或输入 → 校验 → 再 dump；禁止盲点坐标。\n" +
          "order: 50\n",
      )
      Log.i(TAG, "phone-control preset seeded -> " + dir.absolutePath)
    } catch (t: Throwable) {
      Log.w(TAG, "phone-control preset seeding failed", t)
    }
  }

  fun ensurePrivateDshData(): File {
    val dshData = dshDataDir
    val privateDsh = File(homeDir, ".dsh")
    privateDsh.mkdirs()
    seedPhoneControlPreset(privateDsh)
    val privateMarker = File(privateDsh, ".private-layout")
    if (privateMarker.exists()) {
      ensurePublicExportRepo(dshData)
      return privateDsh
    }
    if (isLegacyPublicLayout(dshData, privateDsh)) {
      try {
        reverseMigrate(dshData, privateDsh)
        privateMarker.writeText("private")
        ensurePublicExportRepo(dshData)
        Log.i(TAG, "dshdata reverse migration done -> " + privateDsh.absolutePath)
      } catch (t: Throwable) {
        // A migration failure must not block startup: DSH_HOME stays private, the engine works, retry later.
        Log.e(TAG, "dshdata reverse migration failed; keeping public data", t)
      }
    } else {
      // Clean install or already-private layout: just mark it, no migration needed.
      try {
        privateMarker.writeText("private")
      } catch (t: Throwable) {
        Log.w(TAG, "private layout marker write failed", t)
      }
      ensurePublicExportRepo(dshData)
    }
    return privateDsh
  }

  /** Detect the pre-v0.10.4 public migration layout. */
  private fun isLegacyPublicLayout(dshData: File, privateDsh: File): Boolean {
    if (File(dshData, ".migrated-from").exists()) return true
    for (name in listOf("sessions", "storages", "attachments")) {
      if (isSymlink(File(privateDsh, name))) return true
    }
    for (profile in listOf("web", "headless")) {
      for (name in listOf("cordis.yml", "cordis.patch.yml")) {
        if (isSymlink(File(privateDsh, "profiles/$profile/$name"))) return true
      }
    }
    return false
  }

  /** Reverse migration: copy public data back into private storage, clean up the public leftovers. */
  private fun reverseMigrate(dshData: File, privateDsh: File) {
    for (name in listOf("sessions", "storages", "attachments")) {
      reverseMigrateDir(File(privateDsh, name), File(dshData, name))
    }
    for (profile in listOf("web", "headless")) {
      for (name in listOf("cordis.yml", "cordis.patch.yml")) {
        reverseMigrateFile(
          File(privateDsh, "profiles/$profile/$name"),
          File(dshData, "profiles/$profile/$name"),
        )
      }
    }
    reverseMigrateFile(File(privateDsh, "settings.yaml"), File(dshData, "settings.yaml"))

    // Clean up stale public data (conflicts were renamed *.public-backup, so they're untouched).
    val removedPaths = mutableListOf<String>()
    for (name in listOf("sessions", "storages", "attachments", "profiles", "settings.yaml", ".migrated-from")) {
      val f = File(dshData, name)
      if (f.exists()) {
        removedPaths += f.absolutePath
        if (!f.deleteRecursively()) {
          throw java.io.IOException("failed to delete public path " + f.absolutePath)
        }
      }
    }
    // Tell MediaScanner the old public subdirs are gone, clearing the fake video entries it indexed.
    if (removedPaths.isNotEmpty()) {
      try {
        MediaScannerConnection.scanFile(context, removedPaths.toTypedArray(), null, null)
      } catch (t: Throwable) {
        Log.w(TAG, "media scan cleanup failed", t)
      }
    }
  }

  /** Dir-level reverse migration: drop the private symlink, copy the public entity back with a verified copy, then delete the public source. */
  private fun reverseMigrateDir(privateDir: File, publicDir: File) {
    if (isSymlink(privateDir)) {
      Files.delete(privateDir.toPath())
    }
    if (!publicDir.isDirectory) return
    if (privateDir.isDirectory) {
      if (privateDir.listFiles()?.isNotEmpty() == true) {
        // Conflict: the private entity wins; the public copy is kept aside for review.
        val backup = uniqueBackup(publicDir)
        if (!publicDir.renameTo(backup)) {
          throw java.io.IOException("failed to backup public dir " + publicDir.absolutePath)
        }
        Log.w(TAG, "private " + privateDir.absolutePath + " exists; public kept as " + backup.absolutePath)
        return
      }
      privateDir.deleteRecursively()
    }
    privateDir.parentFile?.mkdirs()
    copyTreeVerified(publicDir, privateDir)
    if (!publicDir.deleteRecursively()) {
      throw java.io.IOException("failed to delete public source " + publicDir.absolutePath)
    }
  }

  /** File-level reverse migration: drop the private symlink, copy the public file back, then delete the public source. */
  private fun reverseMigrateFile(privateFile: File, publicFile: File) {
    if (isSymlink(privateFile)) {
      Files.delete(privateFile.toPath())
    }
    if (!publicFile.isFile) return
    if (privateFile.exists()) {
      if (privateFile.length() > 0) {
        // The public file is the post-migration active copy (settings/profiles); the public one wins,
        // and the stale private entity is kept as a backup rather than silently deleted.
        val backup = uniquePrivateBackup(privateFile)
        if (!privateFile.renameTo(backup)) {
          throw java.io.IOException("failed to backup private file " + privateFile.absolutePath)
        }
        Log.w(TAG, "private file backed up as " + backup.absolutePath)
      } else {
        privateFile.delete()
      }
    }
    privateFile.parentFile?.mkdirs()
    publicFile.copyTo(privateFile, overwrite = true)
    if (privateFile.length() != publicFile.length()) {
      throw java.io.IOException("copy verification failed for " + publicFile.absolutePath)
    }
    if (!publicFile.delete()) {
      throw java.io.IOException("failed to delete public source " + publicFile.absolutePath)
    }
  }

  /** Ensure the public export repo exists: root dir + .nomedia + exports/. */
  private fun ensurePublicExportRepo(dshData: File) {
    try {
      dshData.mkdirs()
      File(dshData, ".nomedia").writeText("")
      File(dshData, "exports").mkdirs()
      // 0.13.1 W3/W4：目录布局说明（每次启动刷新，内容随版本演进）。
      File(dshData, "README.txt").writeText(
        "dsh-mobile 共享数据目录（Documents/dshdata）说明\n" +
          "================================================\n" +
          "本目录只存放导出物与日志，应用运行数据（配置/会话/凭据）在应用私有目录，\n" +
          "文件管理器不可见——在本目录改 settings.yaml 不会生效（引擎读不到）。\n\n" +
          "目录布局：\n" +
          "  exports/                 会话与配置的导出物\n" +
          "    config/settings.yaml   配置导出（设置 > 开发者选项 > 导出配置 生成）\n" +
          "                           修改本文件后点「导入配置」即可生效（无需重装）\n" +
          "  log/                     开发者调试日志（默认关，设置 > 开发者选项 开启；含令牌脱敏，"
            + "但仍有命令与模型内容）\n" +
          "  diagnostics/             启动失败/崩溃时自动生成的诊断包（engine.log 脱敏副本 + 环境信息 + logcat），\n" +
          "                           令牌已替换为 ***，反馈 issue 时直接整目录打包上传即可\n\n" +
          "改配置的正确途径：设置界面各项开关；或 导出配置 -> 文件管理器编辑 -> 导入配置；\n" +
          "进阶：设置 > 开发者选项 > 打开控制台（快照内 bash，可直接 vi settings.yaml）。\n",
      )
    } catch (t: Throwable) {
      Log.w(TAG, "public export repo setup failed", t)
    }
  }

  private fun isSymlink(file: File): Boolean = Files.isSymbolicLink(file.toPath())

  private fun uniqueBackup(publicFile: File): File {
    var candidate = File(publicFile.parentFile, publicFile.name + ".public-backup")
    var i = 1
    while (candidate.exists()) {
      candidate = File(publicFile.parentFile, publicFile.name + ".public-backup-" + i)
      i++
    }
    return candidate
  }

  private fun uniquePrivateBackup(privateFile: File): File {
    var candidate = File(privateFile.parentFile, privateFile.name + ".private-backup")
    var i = 1
    while (candidate.exists()) {
      candidate = File(privateFile.parentFile, privateFile.name + ".private-backup-" + i)
      i++
    }
    return candidate
  }

  /** Recursively copy a directory tree, verifying the file count and total size. */
  private fun copyTreeVerified(src: File, dst: File) {
    dst.mkdirs()
    src.listFiles()?.forEach { f ->
      val target = File(dst, f.name)
      if (f.isDirectory) {
        copyTreeVerified(f, target)
      } else {
        f.copyTo(target, overwrite = true)
      }
    }
    val srcFiles = src.walkBottomUp().filter { it.isFile }.toList()
    val dstFiles = dst.walkBottomUp().filter { it.isFile }.toList()
    val srcSize = srcFiles.sumOf { it.length() }
    val dstSize = dstFiles.sumOf { it.length() }
    if (srcFiles.size != dstFiles.size || srcSize != dstSize) {
      throw java.io.IOException("copy verification failed for " + src.absolutePath)
    }
  }

  /**
   * Runtime patches: overlay fix files from assets/patched onto the corresponding snapshot
   * locations (idempotent). Overlayed fixes (all marked by a sentinel string in the target file,
   * so they are re-applied automatically after a snapshot refresh/re-extract):
   *  - attachment-local-index.js: Android link(2) blocked by sepolicy → rename fallback
   *    (rebuilt onto 0.1.2-rc.1 source, 0.13.3 W9; the rc.2-locked asset was erasing the
    *    engine upgrade's own new code, e.g. breaking prompt via stale persistence API)
   *  - (0.13.7fx-1 retirement) web-frontend-index.html: the asset had become the engine's own
   *    dist/index.html verbatim (0.1.5-rc.1 ships index-DuF6ti6g.js / index-DPX2bQLO.css), so the
   *    patch rewrote identical bytes once per snapshot refresh and nothing else. Its hash-adaptive
   *    rewrite also could not follow the npm hash charset (-([A-Za-z0-9]{8}) never matches
   *    index-Df-65__b), so a dist built from the plain package would have been overwritten with
   *    references to bundles that do not exist.
   *  - session-persistence-jsonl-index.js: Android link(2) fallback — rebuilt onto 0.1.2-rc.1
   *    source (0.13.3 W9): link(tmp, finalPath) failure on EACCES/EPERM/ENOTSUP → rename fallback.
   *  - 0.13.3 retirements (both rc.2-locked assets, upstream 0.1.2-rc.1 covers them natively):
   *    primitives (execCommand clipboard fallback is upstream-native) and fs-local
   *    (rename fallback is upstream-native). llm-deepseek remains a dormant legacy asset.
   *  Patches use a content fingerprint (no fixed marker), so an updated asset re-applies on
   *  upgrade instead of being skipped by a stale marker string (the v1→v2 update bug).
   * (v0.12.4 rc8 removed the onImagePicked/llm-deepseek/textzoom patches — rc8's native image
   * request support and no-cache hardening supersede them.)
   */
  private fun applyRuntimePatches() {
    val dshPkgs = File(usrDir, "lib/node_modules/@deepseek-ai/dsh/node_modules/@deepseek-ai")
    applyAssetPatch("patched/attachment-local-index.js",
      File(dshPkgs, "dsh-attachment-local/lib/index.js"))
    applyAssetPatch("patched/session-persistence-jsonl-index.js",
      File(dshPkgs, "dsh-session-persistence-jsonl/lib/index.js"))
  }

  /** Overwrite-style patch: applies when the target differs from the bundled asset (content
   *  fingerprint), so an updated asset re-applies on upgrade instead of being skipped by a stale
   *  marker string (the v1→v2 asset-update failure).
   */
  private fun applyAssetPatch(asset: String, target: File) {
    // Patches track bundle layouts: when the runtime no longer ships the patched package
    // (e.g. dsh-client-ui-primitives dropped from the dependency graph in dsh 0.1.1-rc.1),
    // stop applying instead of littering a dead overlay into to the tree.
    if (!target.parentFile.exists()) {
      Log.i(TAG, "runtime patch skipped (target package absent): $asset")
      return
    }
    val assetBytes = try {
      context.assets.open(asset).use { it.readBytes() }
    } catch (e: Exception) {
      Log.w(TAG, "runtime patch asset missing: $asset")
      return
    }
    if (target.exists() && target.readBytes().contentEquals(assetBytes)) return
    try {
      target.parentFile?.mkdirs()
      target.writeBytes(assetBytes)
      Log.i(TAG, "runtime patch applied/updated: $asset -> $target")
    } catch (e: Exception) {
      Log.e(TAG, "runtime patch failed: $asset", e)
    }
  }


  /** Append-style patch (for cordis.patch.yml, keeping the user's existing entries). */
  private fun applyAssetPatchAppend(asset: String, target: File, marker: String) {
    if (target.exists() && target.readText().contains(marker)) return
    try {
      val content = context.assets.open(asset).bufferedReader().use { it.readText() }
      target.parentFile?.mkdirs()
      val existing = if (target.exists()) target.readText() else ""
      val sep = if (existing.isNotBlank() && !existing.endsWith("\n")) "\n" else ""
      target.writeText(existing + sep + content)
      Log.i(TAG, "runtime patch appended: $asset -> $target")
    } catch (e: Exception) {
      Log.e(TAG, "runtime patch failed: $asset", e)
    }
  }

  /** Starts the embedded engine. [force] is reserved for a confirmed hung boot
   * after its full cold-start deadline; routine probes must never force-restart. */
  fun startEngine(port: Int = 3080, force: Boolean = false): Boolean {
    // 快照刷新进行中禁止拉起（看门狗旁路闸门）：主流程刷新完成后自会启动；期间拉起只会
    // 起在半新半旧的运行时上。返回 true = 「无需再启动」（与冷却窗语义一致，5s 后看门狗复检）。
    if (EngineManager.snapshotRefreshing) {
      LogCollector.log(TAG, "engine start skipped (snapshot refresh in progress)")
      return true
    }
    // LD_PRELOAD depends on the snapshot's termux-exec lib: when missing, every child exec fails,
    // and combined with the cooldown window that means a silent 90s engine outage — assert explicitly
    // before starting and fail loudly if absent.
    val preload = File(usrDir, "lib/libtermux-exec-ld-preload.so")
    if (!preload.exists()) {
      Log.e(TAG, "engine start failed: termux-exec preload missing at " + preload.absolutePath)
      return false
    }
    val now = System.currentTimeMillis()
    // Process-level CAS: only one concurrent call really starts (device-measured EADDRINUSE double-start).
    if (!STARTING.compareAndSet(false, true)) return true
    // A tracked child proves exactly whether another manager is cold-booting.
    // If it has exited, a caller may retry immediately; deferring on a timestamp
    // alone turns a real early crash into a 90-second outage.
    val withinCooldown = now - EngineManager.lastStartAttemptAt < START_COOLDOWN_MS
    val engineReachable = EngineProbe.portReachable(1_000)
    val managedProcessAlive = engineProcess?.isAlive == true
    if (!force && (engineReachable || managedProcessAlive)) {
      // 0.13.8 #175：DEGRADED_HTTP 阶梯触发时，「端口可连」不再是健康证据——半死引擎
      // 必须允许重启（看门狗/重试路径不带 force 也能走到这里）。
      if (WatchdogV2.degradedHttpTripped()) {
        LogCollector.log(TAG, "engine start allowed despite reachable port: DEGRADED_HTTP ladder tripped (half-dead engine)")
      } else {
        STARTING.set(false)
        LogCollector.log(TAG, "engine start skipped (existing engine reachable or alive)")
        return true
      }
    }
    if (withinCooldown) {
      LogCollector.log(TAG, "engine start retrying after the tracked child exited during cooldown")
    }
    return try {
      // 旧进程清理：无论句柄是否还在，先终结残留（引擎挂死/内存里 fork 掉的孤儿）。
      killExistingEngine()
      // 0.13.1 W5：坏键迁移必须在引擎读 settings 前完成。
      repairSettingsSeed()
      // 0.14.0 #214：退役行 disabled 残留自愈（前置于引擎读 profile；幂等一次性，见函数注释）。
      repairProfilePatch()
      // 0.13.1 W3/W4：共享目录 README 每次启动刷新（此前只在迁移路径调用，正常启动不落盘）。
      ensurePublicExportRepo(dshDataDir)
      applyRuntimePatches()
      // --no-open: the engine must never try to open a desktop browser on Android
      // (the WebView IS the UI). Without it, rc.2's spawn xdg-open on a missing
      // binary stalls engine serve on some emulators (MuMu root observed);
      // the flag is the official engine CLI switch (see bin.js docs).
      val args = arrayOf(
        nodeBin.absolutePath, "--expose-internals", dshBin.absolutePath, "web", "--port", port.toString(), "--no-open",
      )
      engineProcess = startWithArgs(args, shellEnv())
      // The cooldown is written only after a real start: failure paths don't consume the window (retry is immediate).
      EngineManager.lastStartAttemptAt = now
      LogCollector.log(TAG, "engine started")
      true
    } catch (t: Throwable) {
      Log.e(TAG, "engine start failed", t)
      LogCollector.log(TAG, "engine start FAILED: " + (t.message ?: t.javaClass.simpleName))
      // 0.13.1 W3：失败现场镜像到共享目录（此前 engine.log 只在私有域，外界拿不到）。
      mirrorDiagnosticsToShared("engine-spawn-failed")
      false
    } finally {
      STARTING.set(false)
    }
  }

  /**
   * Absolute path of the Host settings document (`$DSH_HOME/settings.yaml`); empty when missing.
   *
   * apk #168：此前取的是**公共导出仓库** `Documents/dshdata/settings.yaml`——那不是配置的落点
   * （配置在私有 `$DSH_HOME`），于是恒返回空串，页面侧接管直接放弃，「打开配置文件」在真机上
   * 一直是坏的。这里换回单一来源。
   */
  fun settingsDocumentPath(): String {
    val file = File(File(homeDir, ".dsh"), "settings.yaml")
    return if (file.isFile) file.absolutePath else ""
  }

  /**
   * apk #168 第二道坎：把活动 settings.yaml **复制到已放行的公共导出目录**并返回副本路径。
   *
   * 为什么不直接放行私有路径：`.dsh` 目录里还有 `.credentials.yaml` / deepseek-key.txt 等凭据，
   * 放宽白名单或 FileProvider 映射会把凭据一并交给系统选择器（安全退化）。复制副本只暴露配置
   * 本身，且副本落在既有白名单 `Documents/dshdata/exports` 内——选择器与 FileProvider 天然可用。
   * 失败返回空串（调用方保持上游错误路径）。
   */
  fun settingsDocumentExport(): String = try {
    val src = File(File(homeDir, ".dsh"), "settings.yaml")
    if (!src.isFile) {
      ""
    } else {
      val dir = File(File(dshDataDir, "exports"), "config").apply { mkdirs() }
      val dst = File(dir, "settings.yaml")
      src.copyTo(dst, overwrite = true)
      dst.absolutePath
    }
  } catch (_: Throwable) {
    ""
  }

  /** The app workspace root (files/home/.dsh/workspaces), created on demand; null when unusable. */
  private fun workspaceRootDir(): File? = try {
    File(context.filesDir, "home/.dsh/workspaces").apply { mkdirs() }.takeIf { it.isDirectory }
  } catch (_: Throwable) {
    null
  }

  /**
   * Spawn the engine, falling back to the system linker when the direct exec
   * is denied: Android 15+ apps targeting SDK 35+ may not exec app-data ELF
   * binaries, but loading them through /system/bin/linker64 is the same
   * mechanism as native libraries (always permitted for app data).
   */
  private fun startWithArgs(args: Array<String>, env: Map<String, String>): Process {
    val log = File(context.filesDir, "engine.log")
    rotateEngineLog(log)
    // P-AC-04（§7.2 启动分段插桩）：t_boot_start 的壳侧起点（落壳侧自有文件
    // files/boot-segments.log）。这次标记即本世代的起点；监听段由 watchEngineListen() 观察
    // （与启动路径解耦），engine.log 本体壳侧一个字都不写。
    LogCollector.markBootStart(context)
    watchEngineListen()
    fun build(argv: List<String>): ProcessBuilder =
      ProcessBuilder(argv).also { b ->
        b.environment().putAll(env)
        // Working directory = the app workspace root (0.13.7fx-1). An Android app process starts
        // in `/`, and the engine takes process.cwd() as the default Session cwd and as the
        // file-reference root for a Session without a workspace — so `@` listed /acct, /apex, …
        // instead of anything the user owns. The workspace root is where the app keeps its
        // workspaces (and the shell write-fence root), so ungrouped Sessions stay inside it.
        workspaceRootDir()?.let { b.directory(it) }
        b.redirectErrorStream(true)
        b.redirectOutput(log)
      }
    return try {
      build(args.toList()).start()
    } catch (e: java.io.IOException) {
      if (e.message?.contains("Permission denied") != true) throw e
      Log.w(TAG, "direct exec denied, falling back to linker64: " + e.message)
      build(listOf("/system/bin/linker64") + args.toList()).start()
    }
  }

  /**
   * 0.13.1 W3：engine.log 世代轮转（保留 3 代）——redirectOutput 语义是每次启动截断，
   * 看门狗 5s 循环重启时崩溃现场每次被清掉，用户永远只剩最后一次的输出。
   */
  /**
   * P-AC-04：监听段（t_listen）观察者。
   *
   * 引擎可被**任何**路径拉起（Activity 启动流 / EngineService 看门狗 / ConsoleActivity），
   * 所以「Web 端口首次应答」的观测挂在 spawn 点而不是某一条启动流里，否则看门狗重启的世代
   * 永远没有 t_listen。单线程、有界 90s（与冷启动预算同量级）后自然退出；每 500ms 一次
   * portReachable(500)（loopback，自带 Proxy.NO_PROXY）。
   */
  private fun watchEngineListen() {
    Thread {
      val deadline = System.currentTimeMillis() + 90_000L
      while (System.currentTimeMillis() < deadline) {
        if (EngineProbe.portReachable(500)) {
          LogCollector.markListen(context)
          return@Thread
        }
        try {
          Thread.sleep(500)
        } catch (_: InterruptedException) {
          return@Thread
        }
      }
    }.apply { isDaemon = true; name = "dsh-engine-listen-watch" }.start()
  }

  private fun rotateEngineLog(log: File) {
    try {
      val prev1 = File(log.parentFile, "engine.log.1")
      val prev2 = File(log.parentFile, "engine.log.2")
      if (prev2.exists()) prev2.delete()
      if (prev1.exists()) prev1.renameTo(prev2)
      if (log.exists()) log.renameTo(prev1)
    } catch (t: Throwable) {
      Log.w(TAG, "engine.log rotation failed", t)
    }
  }

  /** 0.13.1 W3：最近一次死亡的引擎进程退出码（进程活着或句柄丢失时返回 null）。 */
  fun engineExitInfo(): String? {
    val held = engineProcess ?: return null
    if (held.isAlive) return null
    return try {
      "exit=" + held.exitValue()
    } catch (_: Throwable) {
      null
    }
  }

  /**
   * 0.13.1 W3：失败诊断镜像（best-effort，绝不抛出）。把 engine.log 全世代 + 退出码 +
   * 环境/设备信息 + 最近 logcat 写入共享目录 Documents/dshdata/diagnostics/<时间戳>-<原因>/，
   * 用户用文件管理器即可直接复制去反馈（此前全在私有目录，失败时外界拿不到任何现场）。
   * 触发点：spawn 失败 / 进程死亡 / 健康检查超时 / 快照解压失败 / UndoGate 急救。
   */
  fun mirrorDiagnosticsToShared(reason: String) {
    try {
      val ts = java.text.SimpleDateFormat("yyyyMMdd-HHmmss", java.util.Locale.US).format(java.util.Date())
      val dir = File(File(dshDataDir, "diagnostics"), ts + "-" + reason)
      if (!dir.mkdirs() && !dir.isDirectory) return
      val log = File(context.filesDir, "engine.log")
      // 0.13.8 #184：诊断包落共享存储（任何持 All Files Access 的应用可读），engine.log
      // 内含引擎 launch token——副本先过 redact，本体不动（壳侧鉴权链 tokenFromLog 依赖）。
      // #211.3：有界读——原先 readText() → redact → writeText() 的峰值约 3× 单份日志
      // （多 GB 的 engine.log 会 OOM/卡死看门狗线程）；现在按上限读尾部并标注截断。
      for (f in arrayOf(log, File(log.parentFile, "engine.log.1"), File(log.parentFile, "engine.log.2"))) {
        try {
          mirrorLogBounded(f, File(dir, f.name), MIRROR_LOG_LIMIT_BYTES)
        } catch (_: Throwable) {
        }
      }
      try {
        File(dir, "info.txt").writeText(EngineAuth.redact(buildDiagnosticsText(reason)))
      } catch (_: Throwable) {
      }
      try {
        val p = ProcessBuilder("logcat", "-d", "-v", "threadtime", "-t", "400").redirectErrorStream(true).start()
        // 0.13.8 #173：有界读（原 readBytes 无 waitFor，会冻结看门狗调度线程）
        // #211.1：三态结果——超时态写形态标记（不再把已读部分/超时混成同一形态）。
        val out = ProcIo.readBounded(p, 10)
        val body = out.textWithMarkers()
        if (body.isNotEmpty()) File(dir, "logcat-recent.txt").writeText(EngineAuth.redact(body))
      } catch (_: Throwable) {
      }
      LogCollector.log(TAG, "diagnostics mirrored: " + dir.absolutePath)
    } catch (t: Throwable) {
      Log.w(TAG, "diagnostics mirror failed", t)
    }
  }

  private fun buildDiagnosticsText(reason: String): String {
    val sb = StringBuilder()
    sb.append("reason: ").append(reason).append('\n')
    sb.append("time: ").append(java.util.Date().toString()).append('\n')
    try {
      sb.append("app: ").append(BuildConfig.VERSION_NAME).append(" (versionCode ").append(BuildConfig.VERSION_CODE).append(")\n")
    } catch (_: Throwable) {
    }
    sb.append("device: ").append(android.os.Build.MANUFACTURER).append(' ').append(android.os.Build.MODEL)
      .append(" / Android ").append(android.os.Build.VERSION.SDK_INT).append('\n')
    sb.append("abi: ").append(android.os.Build.SUPPORTED_ABIS.joinToString(",")).append('\n')
    engineExitInfo()?.let { sb.append("engine_exit: ").append(it).append('\n') }
    try {
      val probe = EngineProbe.check(500)
      sb.append("probe: ").append(probe.toString()).append('\n')
    } catch (_: Throwable) {
    }
    return sb.toString()
  }

  /**
   * 0.13.1 W5：settings.yaml 坏键迁移。0.13.0 出厂 seed 的 `llm-deepseek:` 裸键（YAML null）
   * 会被首启持久化；fx-1 只修了 APK 内出厂模板，覆盖安装升级的设备上存量坏配置仍在——
   * 引擎 settings section() 抛 TypeError 且被插件加载器吞掉（engine.log 零痕迹），表现为
   * 模型页提供方列表空白 + 「添加提供方」点击无响应（2026-08-28 模拟器双向复现实锤）。
   * 启动前把已知坏裸键修复为空对象；幂等、只触碰已知键、失败不阻塞启动。
   * 判定必须带前瞻：裸键后紧跟缩进子键 = 合法映射（非 null），绝不能改——否则插入重复键
   * DUPLICATE_KEY 直接炸引擎（2026-08-28 首版修复在 fx-1 正常文件上翻车实录）。
   */
  /**
   * 0.14.0 #214 一次性迁移（启动前置）：清除**退役行**残留的 `disabled: true`。
   *
   * 现场：从「曾禁用 ui-layout」的旧版本升上来的设备，live 的
   * `profiles/web/cordis.patch.yml` 里 `- id: ui-layout / disabled: true` 被 0.13.8 的
   * profiles 合并规则永久保留（旧规则「live 内容为基，只追加缺失工厂块」），上游 bundle 的
   * ui-layout 行（布局服务中枢）因此被禁 → 根服务 `layout` 不 activate → 13 条客户端插件全
   * pending（apk #214 截图现场）。这类设备不一定再触发快照刷新（指纹未变则 merge 不跑），
   * 所以自愈必须在引擎读 profile 之前做一次，不能只依赖 [refreshSnapshot]。
   *
   * 边界（与 [FactoryProfilePatch] 一致）：只清退役行 id 的 `disabled: true`；不新增任何
   * disable；用户独有条目与自建 profile 条目不动；改前留同目录 `.pre-<版本>.bak`（回滚路径）；
   * 改动逐条进开发日志；每版本只跑一次（幂等标记），失败不阻塞启动。
   */
  private fun repairProfilePatch() {
    val marker = File(context.filesDir, ".profile-patch-repair-" + BuildConfig.VERSION_NAME)
    if (marker.exists()) return
    try {
      val profilesRoot = File(File(homeDir, ".dsh"), "profiles")
      val targets = (profilesRoot.listFiles() ?: emptyArray())
        .sortedBy { it.name }
        .map { File(it, "cordis.patch.yml") }
        .filter { it.isFile }
      var repaired = 0
      for (target in targets) {
        val live = try { target.readText() } catch (_: Throwable) { continue }
        val result = FactoryProfilePatch.repairRetiredDisabledRows(live)
        if (result.text == live) continue
        val backup = File(target.parentFile, target.name + ".pre-" + BuildConfig.VERSION_NAME + ".bak")
        if (!backup.exists()) {
          try { backup.writeText(live) } catch (_: Throwable) {}
        }
        target.writeText(result.text)
        repaired++
        LogCollector.log(
          TAG,
          "profile patch repaired (" + (target.parentFile?.name ?: "?") + "): " +
            result.changes.joinToString(" | ") + " ; backup=" + backup.name,
        )
      }
      marker.writeText("repaired=" + repaired + " targets=" + targets.size + " at " + System.currentTimeMillis() + "\n")
      if (repaired > 0) {
        LogCollector.log(TAG, "profile patch repair (apk #214): " + repaired + " profile(s) cleaned; marker=" + marker.name)
      }
    } catch (t: Throwable) {
      Log.w(TAG, "profile patch repair failed (non-fatal)", t)
    }
  }

  private fun repairSettingsSeed() {
    try {
      val f = File(File(homeDir, ".dsh"), "settings.yaml")
      if (!f.exists()) return
      val src = f.readText()
      val lines = src.split("\n")
      val out = StringBuilder(src.length + 32)
      var changed = false
      for (i in lines.indices) {
        val line = lines[i]
        val m = Regex("^(llm-deepseek|llm-pi-ai):([ \t]*(#.*)?)$").find(line)
        if (m == null) {
          out.append(line).append('\n')
          continue
        }
        // 前瞻下一个非空行：缩进子键 = 合法映射（非 null），跳过不改。
        // 注意：缩进的【注释行】不构成子键（YAML 注释不参与结构）——fx-1 升级真机的存量
        // 坏 seed 正是「裸键 + 缩进注释」形态（2026-08-29 真机活体实锤），必须穿透注释继续判定。
        val next = lines.drop(i + 1)
          .firstOrNull { it.isNotBlank() && !it.trimStart().startsWith("#") }
        if (next != null && (next.startsWith(" ") || next.startsWith("\t"))) {
          out.append(line).append('\n')
          continue
        }
        when (m.groupValues[1]) {
          "llm-deepseek" -> out.append("llm-deepseek: {}")
          else -> out.append("llm-pi-ai:\n  providers: {}")
        }
        changed = true
        // 保留原行尾注释（如有）。
        val comment = m.groupValues[2]
        if (comment.isNotBlank()) out.append(' ').append(comment.trimStart())
        out.append('\n')
      }
      val fixed = out.toString().removeSuffix("\n")
      if (changed && fixed != src) {
        f.writeText(fixed)
        LogCollector.log(TAG, "settings.yaml repaired: bare null key -> object (0.13.0 seed migration)")
      }
    } catch (t: Throwable) {
      Log.w(TAG, "settings.yaml repair failed (non-fatal)", t)
    }
  }

  /** Stop the engine process (best-effort). */
  fun stopEngine() {
    engineProcess?.destroy()
    engineProcess = null
    LogCollector.log(TAG, "engine stopped (manual)")
    // Reset the cooldown after a manual stop: returning to the foreground should allow an immediate restart.
    EngineManager.lastStartAttemptAt = 0
  }

  /**
   * 引擎进程存活判定（0.13.0 启动超时 D1 的事实源）：进程句柄活着，或 3080 已可达，
   * 即视为「引擎还在」（冷启动 20-45s 中轮询窗口内不许宣判失败）。两者皆否才返回 false。
   * 供 startEngineFlow 的超时语义使用——进程活着就继续等，只有进程死才触发回退。
   */
  fun engineProcessAlive(): Boolean {
    val held = engineProcess
    if (held != null && held.isAlive) return true
    if (held == null) {
      // 句柄丢失（看门狗曾被 fork 或孤儿）：以端口可达性兜底判定。
      // #118 根因3（2026-09）：HTTP 未就绪 ≠ 引擎死亡（冷启动/慢响应实测 3061ms），
      // 必须用端口级 TCP 判定，否则兜底探活把启动中的引擎误判死亡 → 误生成诊断包。
      return EngineProbe.portReachable(1000)
    }
    return false
  }

  /**
   * 终结残留引擎进程：先杀持有句柄的（destroyForcibly + waitFor 有界等待），
   * 再兜底 pkill 快照 node 进程（处理服务/看门狗曾被 fork、句柄已被覆盖的孤儿）。
   * 幂等：无残留时零动作。绝不等待超过 5s（不阻塞启动路径）。
   */
  private fun killExistingEngine() {
    val held = engineProcess
    if (held != null) {
      try {
        held.destroy()
        if (!held.waitFor(3, java.util.concurrent.TimeUnit.SECONDS)) {
          held.destroyForcibly()
          held.waitFor(2, java.util.concurrent.TimeUnit.SECONDS)
        }
      } catch (_: Throwable) {
      }
      engineProcess = null
    }
    // 兜底：命中快照 node 的残留进程（`bin.js web` 是该引擎的唯一形态；pnpm/脚本子进程
    // 不含 bin.js web 特征，不会被误杀）。pkill 不可用时静默跳过。
    // 注：与 UpdateManager 的既有清理（pkill -f bin.js）口径一致。
    try {
      Runtime.getRuntime().exec(arrayOf("/system/bin/pkill", "-f", "bin.js")).waitFor()
    } catch (_: Throwable) {
    }
    // 0.13.8 #175：强制重启前必须复核端口真的释放（坑 31：pkill 在部分 ROM 不生效）——
    // 不释放就 spawn 会 EADDRINUSE 循环。最多等 5s，仍占用则显式记录（下次 tick 重试）。
    repeat(5) {
      if (!EngineProbe.portReachable(1_000)) return
      try { Thread.sleep(1_000) } catch (_: InterruptedException) {}
    }
    LogCollector.log(TAG, "killExistingEngine: port 3080 still occupied after cleanup (release recheck failed)")
  }

  /** Reset the 90s cooldown window: auto-undo (config rollback) or user retry
   *  must be allowed to start the engine immediately. Manual stop already does this. */
  fun resetCooldown() {
    EngineManager.lastStartAttemptAt = 0
  }

  /**
   * Update-manager-v2 probe state machine (PRD F3.2/F1.10): after an online
   * snapshot swap, `usr-old` is kept and `.update-pending` is set. Each engine
   * probe result feeds this: N consecutive healthy ticks finalize (delete the
   * old runtime); a pending window that never turns healthy rolls back to the
   * previous runtime (second-layer fallback; the F3 plugin layer stays in
   * charge of config/plugin-code rollbacks). Never throws.
   */
  fun onEngineProbe(healthy: Boolean) {
    val pending = File(context.filesDir, ".update-pending")
    if (!pending.exists()) {
      updateHealthTicks = 0
      return
    }
    if (healthy) {
      updateHealthTicks++
      if (updateHealthTicks >= UPDATE_CONFIRM_TICKS) {
        pending.delete()
        File(context.filesDir, ".update-pending-at").delete()
        File(context.filesDir, "usr-old").deleteRecursively()
        updateHealthTicks = 0
        LogCollector.log(TAG, "update confirmed: old runtime cleaned (usr-old removed)")
      }
    } else {
      updateHealthTicks = 0
      val at = File(context.filesDir, ".update-pending-at").takeIf { it.exists() }?.readText()?.trim()?.toLongOrNull()
      if (at != null && System.currentTimeMillis() - at > UPDATE_ROLLBACK_MS) {
        rollbackToOld()
        pending.delete()
        File(context.filesDir, ".update-pending-at").delete()
      }
    }
  }

  /** Swap the current runtime back to the kept previous one; restarts the engine from it. */
  private fun rollbackToOld() {
    val usr = File(context.filesDir, "usr")
    val old = File(context.filesDir, "usr-old")
    if (!old.exists()) return
    try {
      val broken = File(context.filesDir, "usr-broken")
      broken.deleteRecursively()
      if (usr.exists()) usr.renameTo(broken)
      if (old.renameTo(usr)) {
        LogCollector.log(TAG, "update rolled back to previous runtime; restarting engine")
        EngineManager.lastStartAttemptAt = 0 // allow an immediate restart (no cooldown stall)
        try { startEngine() } catch (_: Throwable) {
        }
      } else {
        // Rollback of the rollback: the failed old-swap left no usr — put the broken new one back.
        if (!usr.exists() && broken.exists()) broken.renameTo(usr)
        Log.e(TAG, "update rollback failed; usr restored from usr-old: " + usr.exists())
      }
    } catch (t: Throwable) {
      Log.e(TAG, "update rollback threw", t)
    }
  }

  /**
   * Snapshot environment shared by engine/console/log processes (PATH/LD_LIBRARY_PATH/HOME/DSH_HOME/
   * TERMUX_* injected explicitly — the snapshot is self-sufficient, no Termux app needed). Idempotent:
   * safe to call repeatedly (ensurePrivateDshData and the TMPDIR mkdirs are both idempotent).
   */
  fun shellEnv(): Map<String, String> {
    val preload = File(usrDir, "lib/libtermux-exec-ld-preload.so")
    // Cert paths hardcoded at Termux package build time (/data/data/com.termux/...) break after the
    // PREFIX relocation; relocate-snapshot.py doesn't rewrite ELF, so env vars cover the functional
    // paths — curl/wget/git https CA validation depends on them (v0.12.3-FX-2).
    val cert = File(usrDir, "etc/tls/cert.pem").takeIf { it.exists() }
    val certEnv = if (cert != null) {
      mapOf(
        "SSL_CERT_FILE" to cert.absolutePath,
        "CURL_CA_BUNDLE" to cert.absolutePath,
        "GIT_SSL_CAINFO" to cert.absolutePath,
        // 快照 node 编译期硬编码 OpenSSL 配置路径 /data/data/com.termux/...（app 域不可读）：
        // 不注入则任何 node/npm 子进程启动即 OpenSSL configuration error 退出（agent 工具调用
        // npm/node 全部失败，引擎本体侥幸存活）。与 UndoGate/AdbState 同一修复（坑 #5 统一到
        // 引擎级 env，覆盖 agent 所有工具子进程，2026-08-24 真机实测实锤）。
        "OPENSSL_CONF" to File(usrDir, "etc/tls/openssl.cnf").absolutePath,
      )
    } else emptyMap()
    return mapOf(
      "PATH" to (usrDir.absolutePath + "/bin:/system/bin"),
      "LD_LIBRARY_PATH" to (usrDir.absolutePath + "/lib"),
      "HOME" to homeDir.absolutePath,
      // DSH_HOME always stays in the private domain (FUSE forbids symlinks, so the public domain
      // can't maintain the profiles/node_modules flat fallback); all runtime user data lives in private
      // files/home/.dsh, and public Documents/dshdata is only the export repo.
      "DSH_HOME" to ensurePrivateDshData().absolutePath,
      // 0.13.8 #183：引擎子进程读取键盘广播 nonce 的路径基（manage 插件 --es auth 随广播携带）
      "DSH_FILES_DIR" to context.filesDir.absolutePath,
      // os.tmpdir() falls back to the baked-in Termux tmp on Android
      // (unwritable from the app domain); keep spill inside filesDir.
      "TMPDIR" to File(homeDir, "tmp").apply { mkdirs() }.absolutePath,
      // Android 16 forbids exec of app-data ELF regardless of targetSdk
      // (observed on Android 16/vivo: direct exec EACCES even at targetSdk
      // 34). Termux's execve hook re-routes denied execs through
      // /system/bin/linker64 (same mechanism as JNI libs); the snapshot
      // ships libtermux-exec-*-ld-preload.so. The hook only rewrites for
      // untrusted_app_25/27 SELinux domains, so force mode is required.
      "LD_PRELOAD" to preload.absolutePath,
      "TERMUX_EXEC__SYSTEM_LINKER_EXEC__MODE" to "force",
      "TERMUX_EXEC__EXECVE_CALL__INTERCEPT" to "1",
      "TERMUX__ROOTFS" to usrDir.parentFile.absolutePath,
      "TERMUX__PREFIX" to usrDir.absolutePath,
      "TERMUX_APP__DATA_DIR" to context.filesDir.parentFile.absolutePath,
      "TERMUX_APP__LEGACY_DATA_DIR" to "/data/data/com.dsharnessmobile.shell",
      "TERMUX_VERSION" to BuildConfig.TERMUX_VERSION,
      // 版本口径单一来源（2026-09-10 用户定例）：壳侧 UI/桥/诊断都读 BuildConfig.VERSION_NAME，
      // 引擎侧插件（如 android-linux-env 导出的环境配方）一律读这两个环境变量，
      // 不许再出现「界面显示 0.13.x 而插件里写 0.13.0」这类内部口径分裂。
      "DSH_APP_VERSION" to BuildConfig.VERSION_NAME,
      "DSH_APP_VERSION_CODE" to BuildConfig.VERSION_CODE.toString(),
      // Directory-picker endpoint auth token (validated by the web-compat plugin via x-dsh-pick-token).
      "DSH_PICK_TOKEN" to (pickToken ?: ""),
      // ADB 授权状态（0.13.0 F1.7）：dsh-android-bridge 插件据此失败关闭；门控=完全访问档位+开关+配对。
      "DSH_ADB_ALLOW" to (if (AdbState.allowSwitch(context)) "1" else "0"),
      "DSH_ADB_PAIRED" to (if (AdbState.paired(context)) "1" else "0"),
      "DSH_ADB_WIRELESS" to (if (AdbState.paired(context)) "1" else "0"),
      // 门1「完全访问档位」= All Files Access（系统权限）——引擎侧判定与壳侧 AdbState.fullAccess() 同源
      // （审校 C6 语义分裂修复：此前引擎把「写面档位」误当门1，见 review 文档）；授予后重启引擎生效。
      "DSH_ADB_FULLACCESS" to (if (AdbState.fullAccess()) "1" else "0"),
      // Vision backend (Qwen-VL) API key: read from a private file rather than hardcoded in source.
      "DASHSCOPE_API_KEY" to (File(context.filesDir, "dashscope-key.txt").takeIf { it.exists() }?.readText()?.trim() ?: ""),
      // DeepSeek 官方 provider（dsh-llm-deepseek，provider=deepseek-official）：同模式私有文件注入。
      "DEEPSEEK_API_KEY" to (File(context.filesDir, "deepseek-key.txt").takeIf { it.exists() }?.readText()?.trim() ?: ""),
      // node 预热（0.13.0 启动提速 D3）：v8 模块编译缓存——引擎/工具子进程首启自动生成、
      // 二次冷启动命中，直接缩短 node 冷启 require 树编译时间（K20 Pro 实测每次冷启都慢、
      // 0.13.0 之前全快；缓存目录持久在 home/.dsh 下，随用户数据保留不随快照）。
      "NODE_COMPILE_CACHE" to File(ensurePrivateDshData(), ".node-compile-cache").apply { mkdirs() }.absolutePath,
      // C1（P-AC-03 / §7.2）：libuv 线程池默认 4——fs/crypto/zlib/dns 全挤在这 4 条线程上。
      // 显式取 min(8, cores)（见 uvThreadPoolSize）：零产品语义改动，引擎与所有工具子进程
      // 经 shellEnv() 一并继承。判据：子进程回读 process.env.UV_THREADPOOL_SIZE = min(8, cores)。
      "UV_THREADPOOL_SIZE" to uvThreadPoolSize(Runtime.getRuntime().availableProcessors()).toString(),
    ) + certEnv
  }

  companion object {
    private const val TAG = "dsh-engine"

    /**
     * #130-2：手机操控预设自带的 skill——把 0.13.5 现场实测的流程与纪律固定下来
     * （无障碍/DOM 优先、先验前台、按 ref 而非盲点坐标、动作后必校验、输入单次注入并回读）。
     */
    private val PHONE_CONTROL_SKILL = """
---
name: phone-control
description: 手机操控纪律：无障碍语义树优先、ref 语义点击/输入、动作后必校验、禁止盲点坐标与绕路。
---
# 手机操控流程（DSH 设备控制）

## 固定顺序
1. 会话档位必须是 danger-full-access，否则设备工具一律拒绝（切换入口：会话底部权限芯片 → 完全权限；**不要试图让工具自己提权**，也不要用 Termux/ADB 绕路）。
2. 长流程开始前跑一次 android_env_prepare（关动画 + 启用内嵌 ADB 键盘），之后 dump/tap 更稳。
3. 感知：android_ui_dump（无障碍语义树，首选）→ 若结果是 WebView 容器或目标是 DSH 自己的 Web UI，改用 android_web_dump（DOM 快照）。
4. 卡住时：**先 android_ui_global back**（返回上一级），或 home 回桌面重新进入——子菜单/弹窗/详情页出不来时这是第一步。
5. 动作：android_ui_click / android_ui_input，引用用 ref（id:nN / text:精确文本#k / desc: / rid: / wN / css: / text: / role:）。
6. 校验：工具自带回执（点击回报「已生效 / 未观察到界面变化」；输入回报「回读一致 / 未落地」）——不要假设动作成功。
7. 需要看画面时用 android_screenshot（图像直接随结果返回，不需要再 read_image）。

## 纪律
- 禁止盲点坐标点击；nx/ny 仅作兜底，且必须说明理由。
- 同名节点必须消歧：用 dump 里的 #k 序号（text:设置#2）。
- 抓到的包名与前台不一致时以 dumpsys 为准（uiautomator/无障碍可能抓到覆盖层）。
- 输入只走单次注入 + 回读断言；不要用 keyevent 打字母（中文 IME 会汉字化），不要拆成多段输入。
- dump 失败（重 UI / 播放页常见）时按提示走：先 back 退出重页面，或截图看画面；**不要转去尝试 Termux 或 ADB**（未配对时那条路不存在，只会浪费轮次）。
- 连续两次动作未产生预期变化时停下来重新 dump，并如实汇报当前界面状态，不要继续猜测。
"""

    /** Healthy ticks (each 5s watchdog poll) required before the update-v2 finalize deletes usr-old. */
    const val UPDATE_CONFIRM_TICKS = 3

    /** Pending window before an unhealthy runtime is rolled back (PRD F3: recovery ≤ 3 min). */
    const val UPDATE_ROLLBACK_MS = 180_000L

    /** Watchdog/retry backoff: no new start within this window of the last
     *  attempt. Cold node boot on the phone takes 20-45s (plugin tree + first
     *  bind); a 5s watchdog poll would otherwise race a healthy boot and
     *  double-start the engine (device-observed EADDRINUSE). 90s covers the
     *  slowest observed boot with margin. */
    const val START_COOLDOWN_MS = 90_000L

    /** Process handle shared by every EngineManager in the application process. */
    @Volatile
    private var sharedEngineProcess: Process? = null

    /** Process-level start CAS: visible across EngineManager instances (double-start race guard). */
    val STARTING = java.util.concurrent.atomic.AtomicBoolean(false)

    /** 快照刷新进行中（companion 级：MainActivity 与 EngineService 各持 EngineManager 实例，实例字段
     *  互不可见——同 STARTING CAS 道理）。看门狗自愈拉起在此期间必须止步：刷新先备份再全量解压
     *  （模拟器实测 8 分钟），期间 startEngine 会拿到「解压到一半的运行时」——2026-09-05 用户质询
     *  实锤「引擎先于刷新跑起来」。主流程自身在刷新完成后照常拉起（finally 清标志）。 */
    @Volatile
    var snapshotRefreshing: Boolean = false

    /** Last real start time (epoch ms); the watchdog cooldown-window baseline. */
    @Volatile
    var lastStartAttemptAt: Long = 0

    /**
     * Process-level shared directory-picker auth token (C1 fix, 2026-08-16):
     * generated once, then reused by every EngineManager instance in the process — MainActivity
     * rebuilds and EngineService watchdog engine restarts never lose/rotate the token, so auth stays
     * consistent even after the engine-side fail-closed (empty token → reject) path.
     */
    @Volatile
    var sharedPickToken: String? = null

    /** Get (or generate on first call) the process-level pick token. */
    fun ensurePickToken(): String {
      sharedPickToken?.let { return it }
      val token = java.util.UUID.randomUUID().toString()
      sharedPickToken = token
      return token
    }
  }
}

/**
 * C1（P-AC-03 / §7.2）：libuv 线程池目标值 = min(8, cores)，下限 1（0/负数按 1 处理）。
 *
 * 提到顶层是为了可断言——shellEnv() 需要 Context，JVM 单测拿不到；这里只锁「值」这一半，
 * 「注入进 shellEnv()」那一半由 W3ShellContractTest 的源码扫描锁定。
 */
internal fun uvThreadPoolSize(cores: Int): Int = minOf(8, cores.coerceAtLeast(1))

/** 诊断镜像的单份上限（#211.3）：只需现场尾部；内存峰值从 3× 整份压到 3× 上限内。 */
internal const val MIRROR_LOG_LIMIT_BYTES: Long = 2L * 1024 * 1024

/**
 * 诊断镜像的有界单份复制（#211.3，JVM 单测）：只读 [limitBytes] 上限内的**尾部**字节，
 * 出口过 EngineAuth.redact（launch token 不进共享副本），超限在尾部标注截断。
 * 相比原来的 readText() → redact → writeText()（峰值约 3× 单份日志），这里既不再整份读入，
 * 也不把「读到一半」伪装成完整现场。绝不抛出。
 *
 * @return true = 写出了副本（源缺失/空/写入失败为 false）。
 */
internal fun mirrorLogBounded(src: File, dst: File, limitBytes: Long = MIRROR_LOG_LIMIT_BYTES): Boolean {
  return try {
    if (!src.exists() || !src.isFile) return false
    val len = src.length()
    val limit = limitBytes.coerceAtLeast(1L)
    val start = (len - limit).coerceAtLeast(0L)
    val size = (len - start).toInt()
    if (size <= 0) return false
    val buf = ByteArray(size)
    java.io.RandomAccessFile(src, "r").use { raf ->
      raf.seek(start)
      raf.readFully(buf)
    }
    var text = String(buf, Charsets.UTF_8)
    if (start > 0L) {
      text += "\n[diagnostic mirror truncated: first " + start + " bytes omitted; source " + len + " bytes]\n"
    }
    dst.writeText(EngineAuth.redact(text))
    true
  } catch (_: Throwable) {
    false
  }
}
